language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm install
  - ng build --prod --output-path docs --base-href /Notes/
  - copy ./dist/index.html ./dist/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
