language: node_js
node_js:
  - 'stable'
cache:
  npm: true
  directories:
    - node_modules
script:
  - npm install
  - ng build --prod --base-href "https://culinovic-a.github.io/Notes/"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: master
